### ISSUE TITLE
PCB design files for A13-SOM

### ISSUE THREAD

**Issue by AlexDaniel** [OLIMEX/SOM#1]
I can only see schematics here: https://github.com/OLIMEX/SOM/tree/master/A13/A13-SOM
What about .brd files?

**Comment by DanKoloff** [comment]
Hey there,

The SOM boards designed and manufactured by Olimex LTD are not open-source hardware. If you look at the web-pages of A13-SOM, A20-SOM, RK3188-SOM, etc/ you would notice that they don't have the OSHW logo. Only the reference shields for these boards are open-souce hardware (like A13-SOM-WIFI, A20-SOM-EVB, etc).

This is described in the documentation. More information can also be found here: [https://www.olimex.com/Products/SOM/](https://www.olimex.com/Products/SOM/)

If you are looking for OSHW design with Allwinner A13 - take a look at OLinuXino and LIME boards. For example, A13-OLinuXino and A13-OLinuXino-MICRO are OSWH boards.

Best regards,
Lub/OLIMEX
