### ISSUE TITLE
datasheet of RK3188

### ISSUE THREAD

**Issue by iysheng** [OLIMEX/SOM#2]
Hi，thanks for your work，and i want design a board based on your RK3188-SOM,I can get your schematics, could you provide the datasheet or usermanual of RK3188,i google some thing but no get the right doc.

**Comment by TsvetanUsunov** [comment]
you didn't search hard enough https://github.com/OLIMEX/OLINUXINO/tree/master/DOCUMENTS/RK3188-PDFs

**Comment by iysheng** [comment]
> 
> 
> you didn't search hard enough https://github.com/OLIMEX/OLINUXINO/tree/master/DOCUMENTS/RK3188-PDFs

e, thanks for your reply,
